language: python

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
sudo: required
dist: trusty

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0"
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5-dev
          env: TOXENV=py35
        - python: nightly
          env: TOXENV=py36
        - env: TOXENV=docs

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - pip install --upgrade virtualenv$VENVVER pip$PIPVER setuptools tox
  - tox --notest

script:
  - tox -- -n 8

notifications:
  email:
    on_success: never
    on_failure: always