language: python

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
sudo: required
dist: trusty

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27-proj27
        - python: 3.3
          env: TOXENV=py33-proj33
        - python: 3.4
          env: TOXENV=py34-proj34
        - python: 3.5
          env: TOXENV=py35-proj35
        - python: 3.5-dev
          env: TOXENV=py35-proj35
        - python: nightly
          env: TOXENV=py36-proj36
        - env: TOXENV=docs

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - pip install --upgrade virtualenv tox

script:
  - tox -e $TOXENV

notifications:
  email:
    on_success: never
    on_failure: always