language: python

python: 3.5

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - pip install -U tox

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: always