# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

# based on https://github.com/audreyr/cookiecutter/blob/master/appveyor.yml

# validation page: https://ci.appveyor.com/tools/validate-yaml

environment:
  matrix:
    - platform: x86
      PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      TOX_ENV: "27"

    - platform: x64
      PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      TOX_ENV: "34"


init:
  - set PATH=C:\msys64\usr\bin;%PYTHON%;%PYTHON%\Scripts;%PATH%
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
  - python -V
  - "%PYTHON%/python -c \"import struct;print(8 * struct.calcsize(\'P\'))\""

install:
  - set MINICONDAPATH=C:\Miniconda
  - ps: If ($env:Platform -Match "x64") {$env:MINICONDAPATH="C:\Miniconda-x64"}
  - set PATH=%MINICONDAPATH%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

# create and activate Conda virtualenv
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION%
  - activate python%PYTHON_VERSION%
  - python -V

# install dependencies
  - conda install -q --name python%PYTHON_VERSION% setuptools wheel numpy scipy
  - pip install cookiecutter
  - pip install -r {{cookiecutter.project_slug}}/tests/requirements-test.txt
  - pip install -r {{cookiecutter.project_slug}}/requirements.txt

before_test:
  - python -c "import numpy as np;print(np.version.version)"
  - python -c "import scipy as sp;print(sp.version.version)"

build: false

test_script:
  - C:\msys64\usr\bin\bash -c "test/test_create_project_win.sh %TOX_ENV%"